name: Create DXT Release

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: false
        default: 'latest'

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run type checking
      run: npm run typecheck

    - name: Build project
      run: npm run build

    - name: Install DXT CLI
      run: npm install -g @anthropic/dxt

    - name: Create DXT package
      run: npm run package:dxt

    - name: Get package info
      id: package-info
      run: |
        PACKAGE_NAME=$(node -p "require('./package.json').name.replace('@', '').replace('/', '-')")
        PACKAGE_VERSION=$(node -p "require('./package.json').version")
        echo "name=${PACKAGE_NAME}" >> $GITHUB_OUTPUT
        echo "version=${PACKAGE_VERSION}" >> $GITHUB_OUTPUT
        echo "filename=${PACKAGE_NAME}-${PACKAGE_VERSION}.dxt" >> $GITHUB_OUTPUT

    - name: Upload DXT artifact
      uses: actions/upload-artifact@v4
      with:
        name: dxt-package
        path: "*.dxt"
        retention-days: 90

    - name: Upload to release (if triggered by release)
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ steps.package-info.outputs.filename }}
        asset_name: ${{ steps.package-info.outputs.filename }}
        asset_content_type: application/octet-stream
